#########################################################################
###################### CerebralCortex Core Config #######################
#########################################################################

cassandra:
  host: 127.0.0.1
  port: 9042
  keyspace: cerebralcortex
  db_user: ""
  db_pass: ""
  datapoint_table: data

hdfs:
  host: 127.0.0.1
  port: 9009
  raw_files_dir: ""
  hdfs_user: ""
  hdfs_kerb_ticket: ""


influxdb:
  host: 127.0.0.1
  port: 8086
  database: cerebralcortex_raw
  db_user: ""
  db_pass: ""

mysql:
  host: 127.0.0.1
  port: 3306
  connection_pool_name: "CC_Pool"
  connection_pool_size: 1
  database: cerebralcortex
  db_user: root
  db_pass: random_root_password
  datastream_table: stream
  kafka_offsets_table: kafka_offsets
  processing_module_table: processing_module
  user_table: user
  study_table: study

minio:
  host: 127.0.0.1
  port: 9000
  access_key: 'eiyLwkdFUnCw2V48KiUR'
  secret_key: '4W6gs8eyOEMmVIj1pBhc'
  secure: False #ssl

logging:
  log_path: '/var/log/cerebralcortex/' # make sure directory is writeable by current OS user

data_ingestion:
  influxdb_in: True
  nosql_in: False # for now, this cannot be False
  nosql_store: "hdfs" # acceptable parameters are: cassandra, scylladb, hdfs

influxdb_blacklist: # influxdb data ingestion pipeline will not process stream names defined here
  motionsense_hrv_accel_right: "ACCELEROMETER--org.md2k.motionsense--MOTION_SENSE_HRV--RIGHT_WRIST"
  motionsense_hrv_accel_left: "ACCELEROMETER--org.md2k.motionsense--MOTION_SENSE_HRV--LEFT_WRIST"
  motionsense_hrv_gyro_right: "GYROSCOPE--org.md2k.motionsense--MOTION_SENSE_HRV--RIGHT_WRIST"
  motionsense_hrv_gyro_left: "GYROSCOPE--org.md2k.motionsense--MOTION_SENSE_HRV--LEFT_WRIST"
  motionsense_hrv_led_quality_right: "DATA_QUALITY--LED--org.md2k.motionsense--MOTION_SENSE_HRV--RIGHT_WRIST"
  motionsense_hrv_led_quality_left: "DATA_QUALITY--LED--org.md2k.motionsense--MOTION_SENSE_HRV--LEFT_WRIST"
  motionsense_hrv_led_right: "LED--org.md2k.motionsense--MOTION_SENSE_HRV--RIGHT_WRIST"
  motionsense_hrv_led_left: "LED--org.md2k.motionsense--MOTION_SENSE_HRV--LEFT_WRIST"
  phone_accel: "ACCELEROMETER--org.md2k.phonesensor--PHONE"
  phone_gyro: "GYROSCOPE--org.md2k.phonesensor--PHONE"
  autosense_battery: "BATTERY--org.md2k.autosense"
  autosense_ecg: "ECG--org.md2k.autosense"
  autosense_rip: "RIP--org.md2k.autosense"
  autosense_accel_x: "ACCELEROMETER-X--org.md2k.autosense"
  autosense_accel_x: "ACCELEROMETER-Y--org.md2k.autosense"
  autosense_accel_x: "ACCELEROMETER-Z--org.md2k.autosense"
  autosense_gyro: "GYRO--org.md2k.autosense"

#########################################################################
########################### KAFKA Config ################################
#########################################################################
kafkaserver:
  host: 127.0.0.1
  port: 9092
#########################################################################
################ CerebralCortex API SERVER Config #######################
#########################################################################

apiserver:
  host: 0.0.0.0
  port: 8088
  secret_key: 'super-secret'
  token_expire_time: 40000 #seconds
  debug: True

routes:
  auth: "auth"
  stream: "stream"
  object: "object"

#################### TESTING PARAMS ########################
mode:
  run: "productionss"
